# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9de7e82428c72b4560a26848aaabb6061845f24d977c4052d512875bc69d484fa6806e17d0ffc161fdeecedb0b585744e68b6ac562453e90eed063961a184c59

test:
  secret_key_base: 55cfa7be52f2b874079f13511d7fdf7aa383fc9db4b044292dca1123a304675d5bf323f23fd7d80acf01e0c360fdb42a2da1612ae51d3ff79b644b2aa5ff3621

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
